name: viammundi_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/temp/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          # style: regular
    - family: Ceviche_One
      fonts:
        - asset: assets/fonts/Ceviche_One/CevicheOne-Regular.ttf
          # weight: nose

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#   fonts:
#     - family: Roboto
#       fonts:
#         - asset: assets/fonts/Roboto-Regular.ttf
#         - asset: assets/fonts/Roboto-Bold.ttf
#           weight: 700
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Regular.ttf
#         - asset: assets/fonts/Poppins-Bold.ttf
#           weight: 700
#         - asset: assets/fonts/Poppins-Black.ttf
#           weight: 900
#         - asset: assets/fonts/Poppins-Italic.ttf
#           style: italic